before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build QuestionnairesApi/QuestionnairesApi.csproj

configuration:
  - Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

platform:
  - Any CPU
