image:
  - Visual Studio 2017

platform:
  - Any CPU

branches:
  only:
    - master
    - production

environment:
  nuget:
    secure: lAOgXBlidUDKDMFlDJInIUO7K9vZc4FHLP715QyBp1gP9KFNQjntN70Jo6gi4+bA

version: 1.4.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'

install:
  - pwsh: mkdir src/QuestionnairesAPI/wwwroot/min

build_script:
  - pwsh: dotnet build --configuration Release

on_success:
  - pwsh: dotnet nuget push src/AD.Questionnaires/bin/release/AD.Questionnaires.${env:appveyor_build_version}.nupkg --source https://www.nuget.org/api/v2/package --api-key ${env:nuget}